DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE CUSTOMERS (
CUSTOMER_ID INT PRIMARY KEY,
CUSTOMER_NAME VARCHAR(30) NOT NULL,
CITY VARCHAR(30) NOT NULL
);

CREATE TABLE ORDERS (
ORDER_ID INT PRIMARY KEY,
CUSTOMER_ID INT,
ORDER_AMOUNT DECIMAL(100,2) NOT NULL,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

INSERT INTO CUSTOMERS(CUSTOMER_ID,CUSTOMER_NAME,CITY) VALUES
(1,'ANMOL','DEHRADUN'),
(2,'RAHUL','MUMBAI'),
(3,'AUGUSTYA','DELHI'),
(4,'SAHIB','DELHI'),
(5,'DEVANSH','MUMBAI'),
(6,"NONE","NOWHERE");

SELECT * FROM CUSTOMERS;

INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_AMOUNT) VALUES
(1,1,4500.00),
(2,2,2300.00),
(3,3,6700.00),
(4,1,1700.00),
(5,4,6900.00),
(6,5,3200.00),
(7,99,500.00);

SELECT * FROM ORDERS;

--4.1:CUSTOMERS WHO PLACED ORDERS(INNER JOIN)

SELECT
C.CUSTOMER_ID,
C.CUSTOMER_NAME,
C.CITY,
O.ORDER_ID,
O.ORDER_AMOUNT
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID;

--4.2:ALL CUSTOMERS AND THEIR ORDERS(LEFT JOIN)

SELECT
C.CUSTOMER_ID,
C.CUSTOMER_NAME,
C.CITY,
O.ORDER_ID,
O.ORDER_AMOUNT
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID;

--4.3:ALL ORDERS WITH CUSTOMER DETAILS(RIGHT JOIN)

SELECT
O.ORDER_ID,
O.ORDER_AMOUNT,
C.CUSTOMER_ID,
C.CUSTOMER_NAME,
C.CITY
FROM CUSTOMERS C
RIGHT JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID;

--4.4:ALL POSSIBLE COMBINATIONS (FULL OUTER JOIN)

SELECT
C.CUSTOMER_ID,
C.CUSTOMER_NAME,
C.CITY,
O.ORDER_ID,
O.ORDER_AMOUNT
FROM CUSTOMERS C
LEFT JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID

UNION

SELECT
C.CUSTOMER_ID,
C.CUSTOMER_NAME,
C.CITY,
O.ORDER_ID,
O.ORDER_AMOUNT
FROM CUSTOMERS C
RIGHT JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID;

--4.5:Q(V): CUSTOMERS FROM THE SAME CITY(SELF JOIN)

SELECT
C1.CUSTOMER_NAME AS CUSTOMER_1,
C2.CUSTOMER_NAME AS CUSTOMER_2,
C1.CITY AS SHARED_CITY
FROM CUSTOMERS C1
JOIN CUSTOMERS C2
ON  C1.CITY=C2.CITY
AND C1.CUSTOMER_ID<C2.CUSTOMER_ID
ORDER BY C1.CITY;

--5.1:CUSTOMERS WHO NEVER PLACED ORDERS

SELECT
C.CUSTOMER_ID,
C.CUSTOMER_NAME,
C.CITY
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
WHERE O.ORDER_ID IS NULL;

--5.2:CITIES WITH HIGHEST NUMBER OF ORDERS

SELECT
C.CITY,
COUNT(O.ORDER_ID) AS TOTAL_ORDERS,
SUM(O.ORDER_AMOUNT) AS TOTAL_REVENUE,
AVG(O.ORDER_AMOUNT) AS AVG_ORDER_VALUE
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CITY
ORDER BY TOTAL_ORDERS DESC;